name: Build, Tag, and Release Application

on:
  push:
    tags:
      - "v*.*.*-*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Get Version from Makefile
        id: get_version
        run: |
          VERSION=$(make -s version | grep 'Version:' | awk '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Build for GitHub Actions
        env:
          PRIVATE_GPG_KEY_GIST_URL: ${{ secrets.PRIVATE_GPG_KEY_GIST_URL }}
          PRIVATE_PGP_KEY_PASSPHRASE: ${{ secrets.PRIVATE_PGP_KEY_PASSPHRASE }}
          VERSION: ${{ env.VERSION }}
          COMMIT: ${{ env.COMMIT }}
          DATE: ${{ env.DATE }}
        run: |
          set -e
          if [ -z "$PRIVATE_GPG_KEY_GIST_URL" ]; then
            echo "Error: PRIVATE_GPG_KEY_GIST_URL is empty or not set."
            exit 1
          fi
          if [ -z "$PRIVATE_PGP_KEY_PASSPHRASE" ]; then
            echo "Error: PRIVATE_PGP_KEY_PASSPHRASE is empty or not set."
            exit 1
          fi
          curl -s "$PRIVATE_GPG_KEY_GIST_URL" -o src/crypto/privkey.pem
          if [ ! -s src/crypto/privkey.pem ]; then
            echo "Error: Failed to download the private GPG key from the Gist."
            exit 1
          fi
          echo "$PRIVATE_PGP_KEY_PASSPHRASE" > src/crypto/passphrase.txt
          tr -d '\n' < src/crypto/passphrase.txt > tmp
          mv tmp src/crypto/passphrase.txt

          make build_gh_actions

          rm -f src/crypto/privkey.pem src/crypto/passphrase.txt

      - name: Create or Update Git Tag
        id: create_tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.VERSION }}
          message: "Release ${{ env.VERSION }}"
          force_push_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            A new release of the application is now available.
            - Version: ${{ env.VERSION }}
          draft: false
          prerelease: ${{ secrets.PRE_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux x64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-ts-linux-x64
          asset_name: ksau-ts-linux-x64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-ts-linux-arm64
          asset_name: ksau-ts-linux-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows x64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-ts-windows-x64.exe
          asset_name: ksau-ts-windows-x64.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Darwin x64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-ts-darwin-x64
          asset_name: ksau-ts-darwin-x64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Darwin ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ksau-ts-darwin-arm64
          asset_name: ksau-ts-darwin-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
